name: peridigm-preprocess
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gmsh>=4.11
  - python-gmsh>=4.11
  - meshio>=5.3
  - netcdf4>=1.6
  - numpy>=1.24
  - pyyaml>=6.0
  - pip
  - pip:
      - -e .
